### PR TITLE
Test part2 for edit, update and clear all completed.

### PR DESCRIPTION
**Pull request by mandelatuks**
###  in this pull request I and @JauJau088, the following were done

- Use jest framework for testing.
- Create a test file (edit-update-clear.test.js) for a file containing the following functions:
    - a function for editing the task description.
    - a function for updating an item's 'completed' status.
    - the "Clear all completed" function.
- Use the mock storage object we have created in Part 1 of this project to mock the localStorage updates.
-  Mock the HTML elements to test DOM manipulation functions.
- Group the tests using the describe() method.

### CODE REVIEW

**Review by elyor-doniyorov — CHANGES_REQUESTED** [review]
Hi @mandelatuks and @JauJau088, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✔️ There are no linter errors
✔️ All functions for editing task, updating status and 'clear all completed' are tested
✔️ etc.

## Required Changes ♻️
- [ ] In the `Getting started` section of the Readme file. in order to make it professional please add every steps of cloning the project and how to use it. For example, using `git clone <repo link>`, `npm test` command for testing, `npm start` for running the server.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mandelatuks** [comment]
@elyor-doniyorov 
Done updating the READMe.md

**Comment by ShoiraTa** [comment]
## **STATUS: APPROVED  🟢 ** 
------
### Hi @team , 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

5SW

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mandelatuks** [comment]
@ShoiraTa 
thanks so much and happy coding 🤓

**Comment by JauJau088** [comment]
Cheers guys 🥂 

I am merging it now. Thanks for your contributions!

**Pull request merged**
